name: Deployment

concurrency: hosting

on:
  schedule:
    - cron:  '0 0,6,12,18 * * *'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: hosting
    steps:
      - name: req
        
