name: Deployment

concurrency: hosting

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: hosting
    steps:
      - name: pwd
        run: pip install -r requirements.txt
      - name: deploy
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: python main.py&
