name: Deployment

concurrency: hosting

on:
  push:
    branches:
      master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: hosting
    steps:
      - name: req
        run: pip install -r requirements.txt
      - name: deploy
        run: python main.py&
