name: Deployment

concurrency: hosting

on:
  push:
    branches:
      master

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: hosting
    steps:
      - name: pwd
        run: pwd
      - name: ls
        run: ls
      - name: deploy
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: python main.py&
