name: Deployment

concurrency: hosting

on:
  schedule:
    - cron: '0 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    environment: hosting
    steps:
      - uses: actions/checkout@v2
      - name: req
        run: pip install -r requirements.txt
      - name: deploy
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: python main.py&
